### PR TITLE
adds my bash assignment solution

### PR DESCRIPTION
**Pull request by nuviagithub**
please review

### CODE REVIEW

**Review by leslieotetteh — APPROVED** [review]
GREAT WORK

**Review by franktet — APPROVED** [review]
Great work done

**Comment by ForkahEH** [comment]
Good work

**Review by nuviagithub — COMMENTED** [review]
great job!

**Review by nuviagithub — COMMENTED** [review]
great job!

**Comment by siresquire** [comment]
I'm merging for you

**Pull request merged**
