### PR TITLE
adds my bash assignment solution

### PR DESCRIPTION
**Pull request by ForkahEH**

### CODE REVIEW

**Comment by pdushie** [comment]
LGTM

**Review by Davedtech — APPROVED** [review]
well done

**Review by nuviagithub — APPROVED** [review]
great job!

**Review by bydarkwah — COMMENTED** [review]
lgtm

**Comment by Raybest93** [comment]
good work

**Comment by Goldhrt** [comment]
NW

**Review by kwamede — APPROVED** [review]
good

**Comment by siresquire** [comment]
Merging for you

**Pull request merged**
