### PR TITLE
adds my bash assignment solution

### PR DESCRIPTION
**Pull request by JOMACSIT**

### CODE REVIEW

**Review by siresquire — APPROVED** [review]
Super! LGTM - Twumasi
You can merge now

**Review by Ekakane — APPROVED** [review]
Good job. Nicely done....
Include the script date in future :-)

**Review by AustinOzor — COMMENTED** [review]
Seen. The script will do the work.

**Review by AustinOzor — COMMENTED** [review]
Review done. The script is correct.

**Pull request merged**
